path_code: "workflow/scripts/"
path_geno: "/scratch/gianmauro.cuccuru/genomics_QC_pipeline/results_interval/bed/qc_recoded_harmonised/impute_recoded_selected_sample_filter_hq_var_new_id_alleles_"

sumstats_path:  conf/meta_loci_chr2122.txt
workspace_path: "results/validate_geno"

labels:
  chr_label: "CHR"
  pos_label: "POS"
  snpid_label: "SNPID"
  ea_label: "EA"
  oa_label: "NEA"
  eaf_label: "EAF"
  beta_label: "BETA"
  se_label: "SE"
  p_label: "MLOG10P"
  n_label: "N"

thresholds:
  p1: 1.256913021618904e-11
  p2: 1e-06
  p_cojo: 1.256913021618904e-11
  p_jumper: 1e-04
  p_signif: 2.513826043237808e-10
  p_limit: 1e-04
  ppp: 0.99
  hole: 3000000

NLRP12: 1
build: 37
redefine_region: 0
run_coloc: False